{
 "title": "ActiveMQ",
 "tags": [ "telegraf" ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "datasource", "label": "datasource", "query": "prometheus" }
  ]
 },
 "panels": [
  { "title": "Summary", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Process Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "java_lang_OperatingSystem_ProcessCpuLoad",
     "legendFormat": "{{jolokia_agent_url}}-ProcessCpuLoad"
    },
    {
     "expr": "java_lang_Threading_CurrentThreadCpuTime",
     "legendFormat": "{{jolokia_agent_url}}-SystemCpuLoad"
    },
    {
     "expr": "java_lang_OperatingSystem_SystemLoadAverage",
     "legendFormat": "{{jolokia_agent_url}}-SystemLoadAverage"
    }
   ]
  },
  {
   "title": "Java Memory",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_used",
     "legendFormat": "HeapMemoryUsage_max"
    },
    {
     "expr": "java_lang_Memory_HeapMemoryUsage_max",
     "legendFormat": "HeapMemoryUsage_used"
    }
   ]
  },
  {
   "title": "Total Consumer",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_TotalConsumerCount",
     "legendFormat": "{{jolokia_agent_url}}-TotalConsumerCount"
    }
   ]
  },
  {
   "title": "Total Dequeue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_TotalDequeueCount",
     "legendFormat": "{{jolokia_agent_url}}-TotalDequeueCount"
    }
   ]
  },
  {
   "title": "Total Message",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_TotalMessageCount",
     "legendFormat": "{{jolokia_agent_url}}-TotalMessageCount"
    }
   ]
  },
  {
   "title": "Total Enqueue",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 6, "x": 18, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_TotalEnqueueCount",
     "legendFormat": "{{jolokia_agent_url}}-TotalEnqueueCount"
    }
   ]
  },
  { "title": "Memory", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 } },
  {
   "title": "Memory Pool Collection",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 0, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "java_lang_MemoryPool_CollectionUsage_max",
     "legendFormat": "{{pool_name}}-MAX"
    },
    {
     "expr": "jvm_memory_pool_collection_max_bytes",
     "legendFormat": "{{pool_name}}-Used"
    }
   ]
  },
  {
   "title": "Memory Pool Usage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 8, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    { "expr": "jvm_memory_pool_bytes_max", "legendFormat": "{{pool_name}}-MAX" },
    { "expr": "jvm_memory_pool_bytes_init", "legendFormat": "{{pool_name}}-Used" }
   ]
  },
  {
   "title": "Memory Pool PeakUsage",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 8, "x": 16, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "decbits" } },
   "targets": [
    {
     "expr": "java_lang_MemoryPool_PeakUsage_max",
     "legendFormat": "{{pool_name}}-MAX"
    },
    {
     "expr": "java_lang_MemoryPool_PeakUsage_used",
     "legendFormat": "{{pool_name}}-Used"
    }
   ]
  },
  { "title": "Broker", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Broker Store",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_StoreLimit",
     "legendFormat": "{{jolokia_agent_url}}-StoreLimit"
    },
    {
     "expr": "org_apache_activemq_Broker_StorePercentUsage",
     "legendFormat": "{{jolokia_agent_url}}-StorePercentUsage"
    }
   ]
  },
  {
   "title": "Broker Temp",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 8, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_TempLimit",
     "legendFormat": "{{jolokia_agent_url}}-TempLimit"
    },
    {
     "expr": "org_apache_activemq_Broker_TempPercentUsage",
     "legendFormat": "{{jolokia_agent_url}}-StorePercentUsage"
    }
   ]
  },
  {
   "title": "Broker Memory",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_MemoryLimit",
     "legendFormat": "{{jolokia_agent_url}}-MemoryLimit"
    },
    {
     "expr": "org_apache_activemq_Broker_MemoryPercentUsage",
     "legendFormat": "{{jolokia_agent_url}}-MemoryPercentUsage"
    }
   ]
  },
  { "title": "Queues", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 } },
  {
   "title": "Queues sizes",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 0, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_QueueSize",
     "legendFormat": "{{name}}-size"
    }
   ]
  },
  {
   "title": "Queues Consumer",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 6, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_TotalConsumerCount",
     "legendFormat": "{{name}}-consumer"
    }
   ]
  },
  {
   "title": "Queues Dequeue",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 12, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_DequeueCount",
     "legendFormat": "{{name}}-dequeue"
    }
   ]
  },
  {
   "title": "Queues Enqueue",
   "type": "bargauge",
   "gridPos": { "h": 6, "w": 6, "x": 18, "y": 36 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "org_apache_activemq_Broker_DequeueCount",
     "legendFormat": "{{name}}-enqueue"
    }
   ]
  }
 ]
}