{
 "title": "MongoDB",
 "description": "MongoDB -> Mongodb_Exporter -> Prometheus -> Grafana.",
 "tags": [
  "prometheus",
  "mongodb_exporter",
  "mongodb"
 ],
 "time": { "from": "now-1h", "to": "now" },
 "panels": [
  {
   "title": "Ressources Globales MongoDB",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "repeat": "env",
   "targets": [
    {}
   ]
  },
  {
   "title": "Instance",
   "type": "stat",
   "description": "Affiche le statut des instances.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_up{env=\"Mongo-PROD\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Disponibilité du serveur.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_uptime{env=\"Mongo-PROD\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Nombre de CPU",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_sys_cpu_num_cpus{env=\"Mongo-PROD\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU System",
   "type": "stat",
   "description": "Charge du CPU pour le système.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(mongodb_sys_cpu_system_ms{env=\"Mongo-PROD\"}[$__rate_interval])/mongodb_sys_cpu_num_cpus{env=\"Mongo-PROD\"}/10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU User",
   "type": "stat",
   "description": "Charge du CPU pour l'utilisateur.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(mongodb_sys_cpu_user_ms{env=\"Mongo-PROD\"}[$__rate_interval])/mongodb_sys_cpu_num_cpus{env=\"Mongo-PROD\"}/10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "stat",
   "description": "Disponibilité du CPU.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(mongodb_sys_cpu_idle_ms{env=\"Mongo-PROD\"}[$__rate_interval])/mongodb_sys_cpu_num_cpus{env=\"Mongo-PROD\"}/10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM + SWAP",
   "type": "stat",
   "description": "Mémoire totale et mémoire virtuelle.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (mongodb_sys_memory_MemTotal_kb{env=\"Mongo-PROD\"}+mongodb_sys_memory_SwapTotal_kb{env=\"Mongo-PROD\"})"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "description": "Mémoire totale.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (mongodb_sys_memory_MemTotal_kb{env=\"Mongo-PROD\"})"
    }
   ]
  },
  {
   "title": "RAM disponible",
   "type": "stat",
   "description": "Mémoire disponible.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (mongodb_sys_memory_MemAvailable_kb{env=\"Mongo-PROD\"})"
    }
   ]
  },
  {
   "title": "Memoire disponible.",
   "type": "stat",
   "description": "Pourcentage de mémoire disponible\nRemarque : sur les noyaux Linux modernes, la quantité de mémoire disponible pour l'application n'est pas la même que la quantité de mémoire libre + mise en cache + tampons.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) ((mongodb_sys_memory_MemAvailable_kb{env=\"Mongo-PROD\"} or (mongodb_sys_memory_MemFree_kb{env=\"Mongo-PROD\"} + mongodb_sys_memory_Buffers_kb{env=\"Mongo-PROD\"} + mongodb_sys_memory_Cached_kb{env=\"Mongo-PROD\"})) / mongodb_sys_memory_MemTotal_kb{env=\"Mongo-PROD\"} * 100)"
    }
   ]
  },
  {
   "title": "RAM libre",
   "type": "stat",
   "description": "Mémoire libre.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (mongodb_sys_memory_MemFree_kb{env=\"Mongo-PROD\"})"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "stat",
   "description": "Mémoire virtuelle.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (mongodb_sys_memory_SwapTotal_kb{env=\"Mongo-PROD\"})"
    }
   ]
  },
  {
   "title": "BUFFER",
   "type": "stat",
   "description": "Mémoire tampon.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (mongodb_sys_memory_Buffers_kb{env=\"Mongo-PROD\"})"
    }
   ]
  },
  {
   "title": "RAM Mongo Utilisée",
   "type": "stat",
   "description": "Mémoire Utilisée par MongoDB",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_mem_resident{env=\"Mongo-PROD\"}"
    }
   ]
  },
  {
   "title": "Connexions ouvertes.",
   "type": "stat",
   "description": "Nombre de connexions entrantes.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg by (env) (mongodb_ss_connections{env=\"Mongo-PROD\",conn_type=\"current\"})"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_wt_cache_percentage_overhead{env=\"Mongo-PROD\"}"
    }
   ]
  },
  {
   "title": "Latence",
   "type": "stat",
   "description": "calecul de la latence",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (env) (\n  rate(mongodb_ss_opLatencies_latency{op_type=\"commands\"}[$__rate_interval])\n  /\n  ignoring(node_load1)\n  rate(mongodb_ss_opLatencies_latency{op_type=\"commands\"}[$__rate_interval])\n)\nor\navg by (env) (\n  irate(mongodb_ss_opLatencies_latency{op_type=\"commands\"}[$__interval])\n  /\n  ignoring(node_load1)\n  irate(mongodb_ss_opLatencies_latency{op_type=\"commands\"}[$__interval])\n)",
     "legendFormat": "{{op_type}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "description": "Requêtes par secondes.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(mongodb_ss_opcounters{env=\"Mongo-PROD\", legacy_op_type!=\"command\"}[$__rate_interval])\n  or\n  irate(mongodb_ss_opcounters{instance=~\"$instance\", legacy_op_type!=\"command\"}[$__rate_interval])\n)"
    }
   ]
  },
  {
   "title": "RAM Mongo Allouée",
   "type": "stat",
   "description": "Mémoire allouée à MongoDB",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_mem_virtual{env=\"Mongo-PROD\"}"
    }
   ]
  },
  {
   "title": "Connexions disponibles.",
   "type": "stat",
   "description": "Pool de connexion disponible sur l'instance.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{env=\"Mongo-PROD\", conn_type=\"available\"}"
    }
   ]
  },
  {
   "title": "Resources Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Connexions.",
   "type": "timeseries",
   "description": "Connexions TCP (entrantes)",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (env) (mongodb_ss_connections{env=\"Mongo-PROD\", conn_type=\"current\"})",
     "legendFormat": "Connexions"
    }
   ]
  },
  {
   "title": "Etat des connexions",
   "type": "stat",
   "description": "Répartition des connexions : Active, Courante (en moyenne) et disponible.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{env=\"Mongo-PROD\", conn_type=~\"current|active|available\"}",
     "legendFormat": "{{conn_type}}"
    }
   ]
  },
  {
   "title": "Temps de latence.",
   "type": "timeseries",
   "description": "Temps de latence moyen des opérations (classées par lecture, écriture ou (autre) commande).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (env, op_type) (\n  rate(mongodb_ss_opLatencies_latency{env=\"Mongo-PROD\"}[$__rate_interval])\n) +\navg by (env, op_type) (\n  irate(mongodb_ss_opLatencies_latency{env=\"Mongo-PROD\"}[5m])\n)",
     "legendFormat": "{{op_type}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "description": "Trafique réseau I/O en MB.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_network_bytesIn{env=\"Mongo-PROD\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(mongodb_ss_network_bytesOut{env=\"Mongo-PROD\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Network I/O - Physical",
   "type": "timeseries",
   "description": "Mesure du trafic réseau physique en entrée/sortie. ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_network_physicalBytesIn{env=\"Mongo-PROD\"}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(mongodb_ss_network_physicalBytesOut{env=\"Mongo-PROD\"}[$__rate_interval])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Disk Reads Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_sys_disks_sda_read_time_ms[$__rate_interval])",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Disk Writes Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "rate(mongodb_sys_disks_sda_write_time_ms[$__rate_interval])",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Mémoire consommée",
   "type": "timeseries",
   "description": "Mémoire consommée  en MB",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "mongodb_ss_mem_resident{env=\"Mongo-PROD\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command Operations",
   "type": "timeseries",
   "description": "Opérations classées par type de protocole hérité (requête, insertion, mise à jour, suppression, obtention supplémentaire). Et (à partir des threads TTL internes) les suppressions de documents/sec par index TTL.",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (env) (rate(mongodb_ss_opcounters{env=\"Mongo-PROD\", legacy_op_type!=\"command\"}[$__rate_interval]) or \nirate(mongodb_ss_opcounters{env=\"Mongo-PROD\", legacy_op_type!=\"command\"}[$__rate_interval]) or \nrate(mongodb_ss_opcounters{env=\"Mongo-PROD\", legacy_op_type!=\"command\"}[$__rate_interval]) or \nirate(mongodb_ss_opcounters{env=\"Mongo-PROD\", legacy_op_type!=\"command\"}[$__rate_interval]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (instance) (rate(mongodb_ss_metrics_ttl_deletedDocuments{env=\"Mongo-PROD\"}[$__rate_interval]) or \nirate(mongodb_ss_metrics_ttl_deletedDocuments{env=\"Mongo-PROD\"}[$__rate_interval]) or\nrate(mongodb_ss_metrics_ttl_deletedDocuments{env=\"Mongo-PROD\"}[$__rate_interval]) or \nirate(mongodb_ss_metrics_ttl_deletedDocuments{env=\"Mongo-PROD\"}[$__rate_interval]))",
     "legendFormat": "ttl_delete"
    }
   ]
  },
  {
   "title": "Query Metrics for $instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 },
   "repeat": "env",
   "targets": [
    {}
   ]
  },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "description": "Docs par seconde, insérés, mis à jour, supprimés ou renvoyés. (N.b. pas 1 pour 1 avec le nombre d'opérations).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (env,doc_op_type) (rate(mongodb_ss_metrics_document{env=\"Mongo-PROD\"}[$__rate_interval]) or \nirate(mongodb_ss_metrics_document{env=\"Mongo-PROD\"}[5m]))",
     "legendFormat": "{{doc_op_type}}"
    }
   ]
  },
  {
   "title": "Répartition par type d'opérations.",
   "type": "timeseries",
   "description": "Répartition par type d'opérations sur les documents.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_document{env=\"Mongo-PROD\"}[$__rate_interval])",
     "legendFormat": "{{doc_op_type}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "timeseries",
   "description": "Opérations en file d'attente en raison d'un verrou.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (env,count_type) (mongodb_ss_globalLock_currentQueue{env=\"Mongo-PROD\"})",
     "legendFormat": "{{count_type}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "timeseries",
   "description": "Un rapport élevé peut indiquer des opérations sous-optimales qui analysent un grand nombre de documents pour n'en renvoyer qu'une petite partie.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_queryExecutor_scanned{env=\"Mongo-PROD\"}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Curseurs.",
   "type": "timeseries",
   "description": "Curseurs ouverts. Inclut les curseurs inactifs.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (env,csr_type) (mongodb_ss_metrics_cursor_open{env=\"Mongo-PROD\"})",
     "legendFormat": "{{csr_type}}"
    }
   ]
  },
  {
   "title": "Nombre d'exécutions.",
   "type": "timeseries",
   "description": "Nombre d'exécutions par seconde par type d'opération.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{env=\"Mongo-PROD\"}[$__rate_interval])",
     "legendFormat": "{{legacy_op_type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_document{env=\"Mongo-PROD\"}[$__rate_interval])",
     "legendFormat": "{{doc_op_type}}"
    }
   ]
  },
  {
   "title": "Alerts",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Assert Events",
   "type": "timeseries",
   "description": "Ce panneau indique le nombre d'événements d'assertions par seconde en moyenne sur la période donnée. Dans la plupart des cas, les assertions sont triviales, mais vous devriez vérifier vos fichiers journaux si ce compteur atteint des sommets où est constamment élevé..",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (env,assert_type) (rate(mongodb_ss_asserts{env=\"Mongo-PROD\"}[$__rate_interval]) or \nirate(mongodb_ss_asserts{env=\"Mongo-PROD\"}[$__rate_interval]))",
     "legendFormat": "{{assert_type}}"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(rate(nmongodb_sys_disks_sda_io_time_ms[$__rate_interval])/1000 or irate(mongodb_sys_disks_sda_io_time_ms[$__rate_interval])/1000)",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "timeseries",
   "description": "Défauts de page mémoire sous Unix ou Window. Pas nécessairement de mongodb.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (env) (rate(mongodb_ss_extra_info_page_faults{env=\"Mongo-PROD\"}[$__rate_interval]) or \nirate(mongodb_ss_extra_info_page_faults{env=\"Mongo-PROD\"}[5m]))\n",
     "legendFormat": "Faults"
    }
   ]
  },
  {
   "title": "getLastError Write Time",
   "type": "timeseries",
   "description": "Nombre et durée totale, par seconde, de l'exécution des commandes getLastError pour confirmer les problèmes d'écriture.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (env) (rate(mongodb_ss_metrics_getLastError_wtime_totalMillis{env=\"Mongo-PROD\"}[$__rate_interval]) or \nirate(mongodb_ss_metrics_getLastError_wtime_totalMillis{env=\"Mongo-PROD\"}[5m]))",
     "legendFormat": "Write Wait Time"
    }
   ]
  }
 ]
}