{
 "title": "UP/DOWN servers",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  { "title": "Windows", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "STEP-EDI",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up {job=\"node_exporter_windows\"} and {server=\"STEP-EDI\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VEN-DB01",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up {job=\"node_exporter_windows\"} and {server=\"VEN-DB01\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "LDAP-API",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up {job=\"node_exporter_windows\"}  and {server=\"LDAP-API\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STEP-MFT",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up {job=\"node_exporter_windows\"} and {server=\"STEP-MFT\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VHD-DW01",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up {job=\"node_exporter_windows\"} and {server=\"VHD-DW01\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STEP-MFTQA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up {job=\"node_exporter_windows\"} and {server=\"STEP-MFTQA\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VHD-FTPEDI",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up {job=\"node_exporter_windows\"} and {server=\"VHD-FTPEDI\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "VHD-RMS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up {job=\"node_exporter_windows\"} and {server=\"VHD-RMS\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "WEB-RMS",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up {job=\"node_exporter_windows\"} and {server=\"WEB-RMS\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  { "title": "Linux", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 } },
  {
   "title": "Cloud-Sync",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporter_linux\"} and {node=\"Cloud-Sync\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PSWEB01",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporter_linux\"} and {node=\"PSWEB01\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STEPNAS01",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporter_linux\"} and {node=\"STEPNAS01\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STEPLB01",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporter_linux\"} and {node=\"STEPLB01\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mongo-PROD",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporter_linux\"} and {node=\"Mongo-PROD\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "PSVHDDB01",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporter_linux\"} and {node=\"PSVHDDB01\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STEPDB",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporter_linux\"} and {node=\"STEPDB\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STEPLB03",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporter_linux\"} and {node=\"STEPLB03\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STEPDB-DEV",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporter_linux\"} and {node=\"STEPDB-DEV\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Mongo-QA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporter_linux\"} and {node=\"Mongo-QA\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STEPDB-QA",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporter_linux\"} and {node=\"STEPDB-QA\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STEPLB04",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 14 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporter_linux\"} and {node=\"STEPLB04\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "STEPLB02",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "up{job=\"node_exporter_linux\"} and {node=\"STEPLB02\"}",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}