{
 "title": "MongoDB",
 "description": "MongoDB -> Mongodb_Exporter -> Prometheus -> Grafana.",
 "tags": [
  "prometheus",
  "mongodb_exporter",
  "mongodb"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "templating": {
  "list": [
   { "name": "datasource", "label": "Data Source", "query": "prometheus" },
   { "name": "instance", "label": "instance", "query": { "query": "label_values(job)" } }
  ]
 },
 "panels": [
  { "title": "Ressources Globales MongoDB", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }, "repeat": "env" },
  {
   "title": "Instance",
   "type": "stat",
   "description": "Instance status",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_up{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "stat",
   "description": "Server availability.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_uptime{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "stat",
   "description": "Number of CPU",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_sys_cpu_num_cores_available_to_process{job=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU System",
   "type": "stat",
   "description": "CPU load for the system.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(mongodb_sys_cpu_system_ms{job=\"$instance\"}[5m])/mongodb_sys_cpu_num_cores_available_to_process{job=\"$instance\"}/10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU User",
   "type": "stat",
   "description": "CPU load for user.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(mongodb_sys_cpu_user_ms{job=\"$instance\"}[5m])/mongodb_sys_cpu_num_cores_available_to_process{job=\"$instance\"}/10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "stat",
   "description": "CPU availability.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "rate(mongodb_sys_cpu_idle_ms{job=\"$instance\"}[5m])/mongodb_sys_cpu_num_cores_available_to_process{job=\"$instance\"}/10",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM + SWAP",
   "type": "stat",
   "description": "Total memory and virtual memory.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (mongodb_sys_memory_MemTotal_kb{}+mongodb_sys_memory_SwapTotal_kb{})",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "RAM",
   "type": "stat",
   "description": "Total memory.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (mongodb_sys_memory_MemTotal_kb{job=\"$instance\"})"
    }
   ]
  },
  {
   "title": "Available RAM",
   "type": "stat",
   "description": "Available memory.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (mongodb_sys_memory_MemAvailable_kb{})"
    }
   ]
  },
  {
   "title": "Memory available.",
   "type": "stat",
   "description": "Percentage of available memory\nNote: on modern Linux kernels, the amount of memory available to the application is not the same as the amount of free memory + cached + buffers.",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) ((mongodb_sys_memory_MemAvailable_kb{} or (mongodb_sys_memory_MemFree_kb{} + mongodb_sys_memory_Buffers_kb{} + mongodb_sys_memory_Cached_kb{})) / mongodb_sys_memory_MemTotal_kb{} * 100)"
    }
   ]
  },
  {
   "title": "Free RAM",
   "type": "stat",
   "description": "Free memory.",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (mongodb_sys_memory_MemFree_kb{})"
    }
   ]
  },
  {
   "title": "SWAP",
   "type": "stat",
   "description": "Virtual memory.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (mongodb_sys_memory_SwapTotal_kb{})"
    }
   ]
  },
  {
   "title": "BUFFER",
   "type": "stat",
   "description": "Buffer memory.",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "deckbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (instance) (mongodb_sys_memory_Buffers_kb{job=\"$instance\"})"
    }
   ]
  },
  {
   "title": "RAM Mongo Utilisée",
   "type": "stat",
   "description": "Memory Used by MongoDB",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_mem_resident{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Open connections.",
   "type": "stat",
   "description": "Number of incoming connections.",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "avg by (env) (mongodb_ss_connections{conn_type=\"current\"})"
    }
   ]
  },
  {
   "title": "Cache",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 12, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_wt_cache_percentage_overhead{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Latency",
   "type": "stat",
   "description": "latency calculation",
   "gridPos": { "h": 4, "w": 4, "x": 16, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg by (env) (\n  rate(mongodb_ss_opLatencies_latency{op_type=\"commands\"}[5m])\n  /\n  ignoring(node_load1)\n  rate(mongodb_ss_opLatencies_latency{op_type=\"commands\"}[5m])\n)\nor\navg by (env) (\n  irate(mongodb_ss_opLatencies_latency{op_type=\"commands\"}[$__interval])\n  /\n  ignoring(node_load1)\n  irate(mongodb_ss_opLatencies_latency{op_type=\"commands\"}[$__interval])\n)",
     "legendFormat": "{{op_type}}"
    }
   ]
  },
  {
   "title": "QPS",
   "type": "stat",
   "description": "Requests per second.",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 9 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(\n  rate(mongodb_ss_opcounters{legacy_op_type!=\"command\"}[5m])\n  or\n  irate(mongodb_ss_opcounters{instance=~\"$instance\", legacy_op_type!=\"command\"}[5m])\n)"
    }
   ]
  },
  {
   "title": "Mongo RAM Allocated",
   "type": "stat",
   "description": "Mongo RAM Allocated",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_mem_virtual{job=\"$instance\"}"
    }
   ]
  },
  {
   "title": "Connections available.",
   "type": "stat",
   "description": "Connection pool available on the instance.",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=\"available\"}"
    }
   ]
  },
  { "title": "Resources Metrics", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 17 } },
  {
   "title": "Connections.",
   "type": "timeseries",
   "description": "TCP Connections (inbound)",
   "gridPos": { "h": 5, "w": 16, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (env) (mongodb_ss_connections{conn_type=\"current\"})",
     "legendFormat": "Connexions"
    }
   ]
  },
  {
   "title": "Connection status",
   "type": "stat",
   "description": "Connection distribution: Active, Current (average) and available.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "mongodb_ss_connections{conn_type=~\"current|active|available\"}",
     "legendFormat": "{{conn_type}}"
    }
   ]
  },
  {
   "title": "Latency time.",
   "type": "timeseries",
   "description": "Average latency of operations (classified by read, write or (other) command).",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "expr": "avg by (env, op_type) (\n  rate(mongodb_ss_opLatencies_latency{}[5m])\n) +\navg by (env, op_type) (\n  irate(mongodb_ss_opLatencies_latency{}[5m])\n)",
     "legendFormat": "{{op_type}}"
    }
   ]
  },
  {
   "title": "Disk Reads Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_sys_disks_vda_read_time_ms[5m])",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Network I/O - Physical",
   "type": "timeseries",
   "description": "Mesure du trafic réseau physique en entrée/sortie. ",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 31 },
   "fieldConfig": { "defaults": { "unit": "bytes" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_network_physicalBytesIn{}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(mongodb_ss_network_physicalBytesOut{}[$__rate_interval])",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Network I/O",
   "type": "timeseries",
   "description": "Trafique réseau I/O en MB.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 38 },
   "fieldConfig": { "defaults": { "unit": "binbps" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_network_bytesIn{}[$__rate_interval])",
     "legendFormat": "__auto"
    },
    {
     "expr": "rate(mongodb_ss_network_bytesOut{}[$__rate_interval])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Disk Writes Completed",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "fieldConfig": { "defaults": { "unit": "KBs" } },
   "targets": [
    {
     "expr": "rate(mongodb_sys_disks_vda_write_time_ms[5m])",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Memory consumed",
   "type": "timeseries",
   "description": "Memory consumed in MB",
   "gridPos": { "h": 7, "w": 7, "x": 0, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "decmbytes" } },
   "targets": [
    {
     "expr": "mongodb_ss_mem_resident{job=\"$instance\"}",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Command Operations",
   "type": "timeseries",
   "description": "Operations categorized by legacy protocol type (query, insert, update, delete, get extra). And (from internal TTL threads) document deletes/sec by index TTL.",
   "gridPos": { "h": 7, "w": 17, "x": 7, "y": 47 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (env) (rate(mongodb_ss_opcounters{legacy_op_type!=\"command\"}[5m]) or \nirate(mongodb_ss_opcounters{legacy_op_type!=\"command\"}[5m]) or \nrate(mongodb_ss_opcounters{legacy_op_type!=\"command\"}[5m]) or \nirate(mongodb_ss_opcounters{legacy_op_type!=\"command\"}[5m]))",
     "legendFormat": "__auto"
    },
    {
     "expr": "avg by (instance) (rate(mongodb_ss_metrics_ttl_deletedDocuments{}[$__rate_interval]) or \nirate(mongodb_ss_metrics_ttl_deletedDocuments{}[$__rate_interval]) or\nrate(mongodb_ss_metrics_ttl_deletedDocuments{}[$__rate_interval]) or \nirate(mongodb_ss_metrics_ttl_deletedDocuments{}[$__rate_interval]))",
     "legendFormat": "ttl_delete"
    }
   ]
  },
  { "title": "Query Metrics for $instance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 }, "repeat": "env" },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "description": "Docs per second, inserted, updated, deleted or returned. (N.b. not 1 to 1 with the number of operations).",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 55 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (env,doc_op_type) (rate(mongodb_ss_metrics_document{}[$__rate_interval]) or \nirate(mongodb_ss_metrics_document{}[5m]))",
     "legendFormat": "{{doc_op_type}}"
    }
   ]
  },
  {
   "title": "Distribution by type of operations.",
   "type": "timeseries",
   "description": "Distribution by type of operations on documents.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 55 },
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_document{}[5m])",
     "legendFormat": "{{doc_op_type}}"
    }
   ]
  },
  {
   "title": "Queued Operations",
   "type": "timeseries",
   "description": "Operations queued due to lock.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "avg by (env,count_type) (mongodb_ss_globalLock_currentQueue{})",
     "legendFormat": "{{count_type}}"
    }
   ]
  },
  {
   "title": "Document Query Executor",
   "type": "timeseries",
   "description": "A high ratio may indicate suboptimal operations that scan a large number of documents to return only a small fraction.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 64 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_queryExecutor_scanned{}[5m])",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Cursors",
   "type": "timeseries",
   "description": "Open cursors. Includes inactive cursors.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (env,csr_type) (mongodb_ss_metrics_cursor_open{})",
     "legendFormat": "{{csr_type}}"
    }
   ]
  },
  {
   "title": "Number of executions.",
   "type": "timeseries",
   "description": "Number of executions per second by operation type.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 72 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_opcounters{}[5m])",
     "legendFormat": "{{legacy_op_type}}"
    }
   ]
  },
  {
   "title": "Document Operations",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 80 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(mongodb_ss_metrics_document{}[5m])",
     "legendFormat": "{{doc_op_type}}"
    }
   ]
  },
  { "title": "Alerts", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 86 } },
  {
   "title": "Assert Events",
   "type": "timeseries",
   "description": "This panel shows the number of assertion events per second on average over the given period. In most cases, assertions are trivial, but you should check your log files if this counter spikes or is consistently high.",
   "gridPos": { "h": 23, "w": 12, "x": 0, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (env,assert_type) (rate(mongodb_ss_asserts{}[5m]) or \nirate(mongodb_ss_asserts{}[5m]))",
     "legendFormat": "{{assert_type}}"
    }
   ]
  },
  {
   "title": "Disk IO Utilization",
   "type": "timeseries",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 87 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "(rate(mongodb_sys_disks_vdb_io_time_ms[5m])/1000 or irate(mongodb_sys_disks_vda_io_time_ms[5m])/1000)",
     "legendFormat": "{{device}} - {{instance}}"
    }
   ]
  },
  {
   "title": "Page Faults",
   "type": "timeseries",
   "description": "Défauts de page mémoire sous Unix ou Window. Pas nécessairement de mongodb.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 93 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg by (env) (rate(mongodb_ss_extra_info_page_faults{}[$__rate_interval]) or \nirate(mongodb_ss_extra_info_page_faults{}[5m]))\n",
     "legendFormat": "Faults"
    }
   ]
  },
  {
   "title": "getLastError Write Time ",
   "type": "timeseries",
   "description": "Nombre et durée totale, par seconde, de l'exécution des commandes getLastError pour confirmer les problèmes d'écriture.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 102 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "avg by (env) (rate(mongodb_ss_metrics_getLastError_wtime_totalMillis{}[$__rate_interval]) or \nirate(mongodb_ss_metrics_getLastError_wtime_totalMillis{}[5m]))",
     "legendFormat": "Write Wait Time"
    }
   ]
  }
 ]
}